"""add account deletion events

Revision ID: 35338f02204a
Revises: 3877a2b5d4ed
Create Date: 2026-08-24 16:35:16.019646

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "35338f02204a"
down_revision: str | None = "3877a2b5d4ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_deletion_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clerk_user_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_deletion_events_clerk_user_id"),
        "account_deletion_events",
        ["clerk_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_account_deletion_events_clerk_user_id"), table_name="account_deletion_events"
    )
    op.drop_table("account_deletion_events")
    # ### end Alembic commands ###
