"""add brief drafts and versions

Revision ID: 3877a2b5d4ed
Revises: a8db34479c31
Create Date: 2026-08-24 16:09:12.181355

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3877a2b5d4ed"
down_revision: str | None = "a8db34479c31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brief_drafts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("fields_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "revision", name="uq_brief_draft_revision"),
    )
    op.create_index(
        op.f("ix_brief_drafts_project_id"), "brief_drafts", ["project_id"], unique=False
    )
    op.create_table(
        "brief_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("fields_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "source_revision", name="uq_brief_version_source"),
        sa.UniqueConstraint("project_id", "version", name="uq_brief_version_number"),
    )
    op.create_index(
        op.f("ix_brief_versions_project_id"), "brief_versions", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_brief_versions_project_id"), table_name="brief_versions")
    op.drop_table("brief_versions")
    op.drop_index(op.f("ix_brief_drafts_project_id"), table_name="brief_drafts")
    op.drop_table("brief_drafts")
    # ### end Alembic commands ###
